### ISSUE TITLE
运行Android example 提示bash: java: command not found

### ISSUE THREAD

**Issue by P-stevens** [sunweisheng/jenkins-json-build#1]
jenkins在docker中运行
进入容器运行java -version是正常的
在pipeline中直接在jenkinsfile中加入sh 'java -version'中也是正常的

为什么在jenkins-project.json中使用 java -version 就会报错呢?

**Comment by sunweisheng** [comment]
java -version的命令有点特殊，需要这么写：
"Script": {
        "输出Java版本": "java -version 2>&1"
      }
将标准输入2（错误）链接到标准输入1（正常）上。

**Comment by P-stevens** [comment]
开始执行[输出Java版本]的[java -version 2>&1]命令
[Pipeline] isUnix
[Pipeline] sh
bash: cannot set terminal process group (6): Not a tty
bash: no job control in this shell
bash: java: command not found

一样会提示错误

**Comment by sunweisheng** [comment]
这个问题是因为没有配置环境变量：
#配置环境变量
vi /etc/profile

JAVA_HOME=/usr/local/java
JRE_HOME=/usr/local/java/jre
PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
export JAVA_HOME JRE_HOME PATH CLASSPATH

#重新加载
source /etc/profile
#检查结果
java -version

详情可以看：https://github.com/sunweisheng/Kvm/blob/master/Install-Java-18.md

**Comment by sunweisheng** [comment]
如果知道Java安装的路径也可以用绝对路径：
安装路径/java -version 2>&1
