### ISSUE TITLE
纯粹多次一举，搞个json让配置更加复杂了

### ISSUE THREAD

**Issue by mamh2021** [sunweisheng/jenkins-json-build#2]
纯粹多次一举，搞个json让配置更加复杂了，
json放代码服务器 ip，port等配置 还是可以的，放的太多就过于麻烦。把公共的 stage 封装好，多个项目共用。

**Comment by sunweisheng** [comment]
感谢你的反馈，这个项目希望可以帮助很多不懂Jenkins或没精力深入研究的人减轻构建的复杂度，正如你所言效果可能并没有太好，我也在思考是否写个客户端工具帮助配置json就能更好的达到目标了。
